# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2b1a5559397be99c54bd2f28946cd87f788ca5deb5208046e55c19348f470bb61dbf15be98621327351de73700b649a3af934d3b714d50cedf7b4a4fb1df4e

test:
  secret_key_base: caa48438a71e2723db146a1d32e2819243430604ddbd0f0bec4a0b0607cfe73bd9708739122ef5514e9e4219e4ba5f84b9c616f6c06dd982530798570be761b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
